name: Run Extraction

on:
  schedule:
    # At 03:00 AM Halifax time every day
    - cron: '0 7 * * *'

jobs:
  extraction-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Extraction.py
        run: python Extraction.py
